name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # download repo
      uses: actions/checkout@v2  

    - name: Set up dependencies # instalar herramientas g++
      run: sudo apt-get install -y build-essential  

    - name: Build the project
      run: make build

    - name: Run script
      run: make run

    - name: Clean
      run: make clean
